# docker compose for development

version: "3.8"

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=tommy
      - POSTGRES_PASSWORD=dBZqy5fG90
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
  back:
    build:
      context: ./backend
      target: runner
    image: rakutan-shirazu-back:latest
    environment:
      DATABASE_URL: postgresql://tommy:dBZqy5fG90@postgres:5432/mydb?schema=public
      FASTIFY_PORT: 8080
    expose:
      - 8080
    depends_on:
      - postgres
  front:
    build:
      context: ./frontend
      target: runner
    image: rakutan-shirazu-front:latest
    expose:
      - 3000
    depends_on:
      - postgres

volumes:
  postgres:
